name: verify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "6 5 * * *"

jobs:
  verify:
    uses: kapricorn-media/github/.github/workflows/zig-verify.yaml@main
    with:
      zig-version: 0.12.0-dev.2063+804cee3b9
